services:
  - type: web
    name: ai-quiz-analyzer
    env: python
    buildCommand: "./venv/Scripts/python.exe -m pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn ai_quiz_analyzer.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
